- README.md
- gulpfile.js
- package.json
- src/decorators.ts
- src/index.ts
- src/interfaces.ts
- src/server.ts
- test/decorators.test.ts
- test/framework.test.ts
- test/server.test.ts
- tsconfig.json
- typings.json
Upgraded dependencies and removed `I` prefix from interfaces.
#256
#256
Build script
> Upgraded dependencies and removed `I` prefix from interfaces.

- README.md
- package.json
- src/constants.ts
- src/decorators.ts
- src/index.ts
- src/server.ts
- test/framework.test.ts
- test/server.test.ts
Required for https://github.com/inversify/InversifyJS/issues/283
> Working on https://github.com/inversify/InversifyJS/issues/283

- README.md
- package.json
- src/server.ts
- test/framework.test.ts
- test/server.test.ts
Updates inversify
inversify/InversifyJS#403
See main issue
Unit tests
> updated to inversify 3.0.0-beta.1

- .vscode/settings.json
- package.json
- src/decorators.ts
- src/index.ts
- src/interfaces.ts
- src/server.ts
- test/decorators.test.ts
- test/framework.test.ts
Remove defaults
inversify/InversifyJS/issues/435
inversify/InversifyJS/issues/435
CI
> 3.0.0-beta.1

- test/framework.test.ts
Reached 100% test coverage 🎉 
https://github.com/inversify/InversifyJS/issues/370
Had some free time to address the issue.
Unit tests pass
> Added more tests to get 100% coverage

- README.md
- package.json
- src/server.ts
- test/server.test.ts
Implements inversify/InversifyJS#478
inversify/InversifyJS#478
inversify/InversifyJS#478
CI + 1 extra unit test
> Implements inversify/InversifyJS#478

- README.md
Looking at the examples in the Readme, my first impression was that response object was not available in the controller methods and that sending a status code other than 200 should be done in some other complex way. Adding this example to the Readme so that it helps others such as myself.
> doc: add example of method sending only statusCode

- src/decorators.ts
- src/interfaces.ts
- src/server.ts
- test/decorators.test.ts
- test/framework.test.ts
https://github.com/inversify/InversifyJS/issues/487
See description in the https://github.com/inversify/InversifyJS/issues/487
> Provide the way to inject middleware to controller/methods

- README.md
- src/server.ts
- test/server.test.ts
This allows passing in a custom express application instance.
https://github.com/inversify/InversifyJS/issues/509
See https://github.com/inversify/InversifyJS/issues/509
> Add ability to pass in a custom existing express application

- README.md
- src/decorators.ts
- test/framework.test.ts
Fixed ReadMe.md error
Fixed Unit test for @Cookies decorator to cover more code
https://github.com/inversify/inversify-express-utils/pull/41
Documentation accuracy
100% Code coverage 
Unit tests
> Minor Fixes for Pull Request #41

- src/server.ts
- test/bugs.test.ts
Bug fix for https://github.com/inversify/InversifyJS/issues/554
Check for empty query parameters and return them as undefined
https://github.com/inversify/InversifyJS/issues/554
allows optional query parameters
unit test
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My change requires a change to the documentation.
> Bug fix for https://github.com/inversify/InversifyJS/issues/554

- .gitignore
- package.json
- test/bugs.test.ts
- test/decorators.test.ts
- test/framework.test.ts
- test/server.test.ts
Updated dependencies
N/A
Updated dependencies
CI
> Updated dependencies

- README.md
Added body parser to example like discussed in [#606](https://github.com/inversify/InversifyJS/issues/606)
Extended getting started
[#606](https://github.com/inversify/InversifyJS/issues/606)
> added body parser to getting started

- package.json
- src/decorators.ts
Fix for https://github.com/inversify/inversify-express-example/pull/250
> Fixed import issue

- README.md
- package.json
- src/constants.ts
- src/decorators.ts
- src/index.ts
- src/server.ts
- src/utils.ts
- test/auth_provider.test.ts
- test/base_http_controller.test.ts
- test/bugs.test.ts
- test/framework.test.ts
- test/http_context.test.ts
- test/server.test.ts
Implements inversify/InversifyJS/issues/687
inversify/InversifyJS/issues/687
inversify/InversifyJS/issues/687
Unit tests and CI
> Implements inversify/InversifyJS/issues/687

- README.md
> Updated docs to match decorator changes

- .travis.yml
- package.json
> Greenkeeper/publish please 3.0.1

- package.json
> chore(package): update supertest to version 3.3.0

- package.json
> chore(package): update moq.ts to version 2.7.3

- package.json
> chore(package): update publish-please to version 5.1.1

- package.json
> chore(package): update publish-please to version 5.4.3

- package.json
> chore(package): update supertest to version 3.4.2

- README.md
It looks like this code 
```    private index(req: express.Request, res: express.Response, next: express.NextFunction): string {```
needs to be changed like this
```    private index(@request() req: express.Request, @response() res: express.Response, @next() next: express.NextFunction): string {```
Or am I missing something?
> Adding in decorators in the README.md code

- .github/workflows/node.js.yml
https://github.com/inversify/InversifyJS/pull/1527
> ci: run ci against node `18.x, 20.x`

- CHANGELOG.md
- package-lock.json
- package.json
- added changelog
- version bump to 6.4.4
- includes #378 / #379
> chore: version 6.4.4

- .publishrc
`test` is wrong , it should be `npm test`
> chore: fix `publish-please` config

- .npmignore
> chore: add non-essential items to `.npmignore`

- package-lock.json
- package.json
version 6.4.5 (fixes publish issue from 6.4.4 see https://github.com/inversify/inversify-express-utils/issues/378#issuecomment-1781894297)
> chore: version 6.4.5

- CHANGELOG.md
- package-lock.json
- package.json
Bump package version.
Releasing the next inversify version.
Tests run successfully.
> Bump package version

- CHANGELOG.md
- src/interfaces.ts
- src/server.ts
Updated `Controller` without wrong constraints.
Fixes inversify/InversifyJS#1669
Fixing related issue
- Tests passes successfully.
> Update Controller without wrong constraints
